//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QL_TapHoaEntities : DbContext
    {
        public QL_TapHoaEntities()
            : base("name=QL_TapHoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChiTietDonHang> tblChiTietDonHangs { get; set; }
        public virtual DbSet<tblDanhMuc> tblDanhMucs { get; set; }
        public virtual DbSet<tblDonHang> tblDonHangs { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHangs { get; set; }
        public virtual DbSet<tblNhaCungCap> tblNhaCungCaps { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanViens { get; set; }
        public virtual DbSet<tblSanPham> tblSanPhams { get; set; }
        public virtual DbSet<tblTrangThaiDon> tblTrangThaiDons { get; set; }
        public virtual DbSet<tblVaiTro> tblVaiTroes { get; set; }
    }
}
