//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietDonHang
    {
        public int ID { get; set; }
        public Nullable<int> MaDon { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> DonGiaLucMua { get; set; }
    
        public virtual tblDonHang tblDonHang { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
