//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTapHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSanPham()
        {
            this.tblChiTietDonHangs = new HashSet<tblChiTietDonHang>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public Nullable<int> MaDM { get; set; }
        public Nullable<int> MaNCC { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public string AnhSP { get; set; }
        public string MoTaChiTiet { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<bool> LaSanPhamMoi { get; set; }
        public Nullable<bool> LaSanPhamNoiBat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietDonHang> tblChiTietDonHangs { get; set; }
        public virtual tblDanhMuc tblDanhMuc { get; set; }
        public virtual tblNhaCungCap tblNhaCungCap { get; set; }
    }
}
